# Generated by Django 6.0.6 on 2026-06-27 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercializadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('direccion_matriz', models.TextField()),
                ('suscripcion_activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('monto_total_tienda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('propietario', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('coordenadas_gps', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('estado_cuenta', models.BooleanField(default=True)),
                ('rol', models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('COMERCIALIZADORA', 'Comercializadora')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionComercializadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_cobrar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_liquidacion', models.DateTimeField(auto_now_add=True)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGADO_COMERCIALIZADORA', 'Pagado a Comercializadora')], default='PENDIENTE_PAGO', max_length=30)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion', to='negocio.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=50)),
                ('precio_mayorista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comercializadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='negocio.comercializadora')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen_origen', models.CharField(max_length=100)),
                ('cantidad_disp', models.PositiveIntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='negocio.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='negocio.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_vendidos', to='negocio.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CampanaRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campana', models.CharField(max_length=100)),
                ('factor_puntos', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='negocio.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_recibidos', to='negocio.tienda'),
        ),
        migrations.AddField(
            model_name='comercializadora',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_comercializadora', to='negocio.usuario'),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_asignada', models.CharField(max_length=100)),
                ('vehiculo_placa', models.CharField(max_length=10)),
                ('puntos_acumulados', models.IntegerField(default=0)),
                ('presupuesto_ventas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to='negocio.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.CharField(choices=[('INGRESO', 'Venta (Ingreso)'), ('EGRESO', 'Canje (Egreso)')], max_length=15)),
                ('puntos_ganados', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_generados', to='negocio.pedido')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_puntos', to='negocio.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_registrados', to='negocio.vendedor'),
        ),
    ]
