# Generated by Django 6.0.6 on 2026-07-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='coordenadas_gps',
        ),
        migrations.AddField(
            model_name='tienda',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=-3.986659, max_digits=9),
        ),
        migrations.AddField(
            model_name='tienda',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=-79.199088, max_digits=9),
        ),
    ]
