# Generated by Django 6.0.6 on 2026-07-24 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_remove_tienda_coordenadas_gps_tienda_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='propietario',
        ),
        migrations.AddField(
            model_name='tienda',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tienda', to='negocio.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('COMERCIALIZADORA', 'Comercializadora'), ('TIENDA', 'Tienda')], max_length=20),
        ),
        migrations.CreateModel(
            name='InventarioTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disp', models.PositiveIntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_tienda', to='negocio.producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='negocio.tienda')),
            ],
            options={
                'unique_together': {('tienda', 'producto')},
            },
        ),
    ]
