# Generated by Django 6.0.6 on 2026-07-25 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0003_remove_tienda_propietario_tienda_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_mayorista',
            new_name='precio',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='negocio.categoria'),
        ),
    ]
