# Generated by Django 6.0.6 on 2026-07-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0004_categoria_rename_precio_mayorista_producto_precio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='sku',
            new_name='codigo',
        ),
    ]
