# Generated by Django 6.0.6 on 2026-07-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0006_categorias_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacioncomercializadora',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente'), ('PAGADO_COMERCIALIZADORA', 'Pagado')], default='PENDIENTE_PAGO', max_length=30),
        ),
    ]
