# Generated by Django 6.0.6 on 2026-07-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0007_alter_liquidacioncomercializadora_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercializadora',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
